version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaccinationdb
      MYSQL_USER: vaccuser
      MYSQL_PASSWORD: vaccpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    image: vaccination-backend:latest
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vaccinationdb
      SPRING_DATASOURCE_USERNAME: vaccuser
      SPRING_DATASOURCE_PASSWORD: vaccpass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: replace_with_secure_secret
    ports:
      - "8080:8080"

  frontend:
    image: frontend:latest
    ports:
      - "4200:80"
    # build: ./frontend (if you have an Nginx Dockerfile to serve Angular build)
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
