server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/vaccinationdb?useSSL=false&allowPublicKeyRetrieval=true
    username: vaccuser
    password: vaccpass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  redis:
    host: redis
    port: 6379

jwt:
  secret: replace_with_a_secure_secret_key
  expirationMs: 3600000

spring:
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
